# Documentação: docker-compose.yml para o Projeto FluxoAI (Arquitetura Microsserviços)

services:
  # Serviço Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2 # Imagem oficial do Mosquitto
    container_name: fluxoai-mosquitto
    ports:
      - "1883:1883" # Porta padrão do MQTT
    restart: unless-stopped
    networks:
      - fluxoai_net
    # A secção 'volumes:' foi removida pois não era necessária e causava erro.

  # Serviço de Captura de Vídeo
  servico_captura:
    build: ./servico_captura
    image: jazonbatista/fluxoai-servico-captura:latest
    container_name: fluxoai-servico_captura
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=1883
      - VIDEO_SOURCE=${VIDEO_SOURCE:-0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - FRAME_WIDTH=${FRAME_WIDTH:-640}
      - FRAME_HEIGHT=${FRAME_HEIGHT:-480}
      - PUBLISH_TOPIC=fluxoai/frames/raw
    depends_on:
      - mosquitto
    devices:
      - "/dev/video0:/dev/video0" # Mapeia a câmara USB
    restart: unless-stopped
    networks:
      - fluxoai_net

  # Serviço de IA (Será modificado para usar MQTT) - POR FAZER
  # servico_ia:
  #   build: ./servico_ia
  #   image: jazonbatista/fluxoai-servico-ia:latest
  #   container_name: fluxoai-servico_ia
  #   environment:
  #     - MQTT_BROKER_HOST=mosquitto
  #     - MQTT_BROKER_PORT=1883
  #     - SUBSCRIBE_TOPIC=fluxoai/frames/raw
  #     - PUBLISH_TOPIC=fluxoai/frames/detected
  #     - LOG_LEVEL=${LOG_LEVEL:-INFO}
  #   depends_on:
  #     - mosquitto
  #   restart: unless-stopped
  #   networks:
  #     - fluxoai_net

  # Serviço de Análise (Será criado) - POR FAZER
  # servico_analise: ...

  # Serviço Web (Será modificado para usar MQTT) - POR FAZER
  # servico_web: ...

networks:
  fluxoai_net:
    driver: bridge

